name: text2speech
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - audioread=2.1.9=py39hf3d152e_0
  - backcall=0.2.0=py_0
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2020.10.14=0
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.5=py39he32792d_0
  - chardet=4.0.0=py39hf3d152e_1
  - cryptography=3.4.7=py39hbca0aa6_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - ffmpeg=4.3.1=hca11adc_2
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=2.10=pyh9f0ad1d_0
  - ipykernel=5.3.4=py39hb070fc8_0
  - ipython=7.22.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.17.2=py39h06a4308_1
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jupyter_client=5.3.3=py_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.3.1=py39h1a9c180_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=9_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - librosa=0.8.1=pyhd8ed1ab_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.3.0=hf544144_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - lz4-c=1.9.3=h9c3ff4c_0
  - matplotlib-base=3.4.2=py39h2fa2bec_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - numba=0.53.1=py39h56b8d98_1
  - numpy=1.20.3=py39hdbf815f_1
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py39hf95b381_1
  - pip=21.1.2=py39h06a4308_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py39hf3d152e_3
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.9.5=h12debd9_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pyzmq=20.0.0=py39h2531618_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3deb0d_0
  - resampy=0.2.2=py_0
  - scikit-learn=0.24.2=py39h4dfa638_0
  - scipy=1.6.3=py39hee8e79c_0
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.4=hdfb4753_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.0.5=py_0
  - tzdata=2020f=h52ac0ba_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=py_0
  - x264=1!161.3030=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - alabaster==0.7.12
    - antlr4-python3-runtime==4.8
    - async-timeout==3.0.1
    - attrdict==2.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - black==19.10b0
    - boto3==1.17.93
    - botocore==1.20.93
    - braceexpand==0.1.7
    - cachetools==4.2.2
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - configparser==5.0.2
    - cython==0.29.23
    - distance==0.1.3
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.17.1
    - editdistance==0.6.0
    - filelock==3.0.12
    - frozendict==2.0.2
    - fsspec==2021.6.0
    - future==0.18.2
    - g2p-en==2.1.0
    - gdown==3.13.0
    - gitdb==4.0.7
    - gitpython==3.1.17
    - google-auth==1.31.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.0
    - h5py==3.2.1
    - huggingface-hub==0.0.8
    - hydra-core==1.0.6
    - imagesize==1.2.0
    - inflect==5.3.0
    - iniconfig==1.1.1
    - ipadic==1.0.0
    - isort==4.3.21
    - jieba==0.42.1
    - jinja2==3.0.1
    - jmespath==0.10.0
    - kaldi-io==0.9.4
    - kaldi-python-io==1.2.2
    - kaldiio==2.17.2
    - latexcodec==2.0.1
    - llvmlite==0.36.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - marshmallow==3.12.1
    - mecab-python3==1.0.3
    - megatron-lm==2.2.0
    - mpmath==1.2.1
    - multidict==5.1.0
    - nemo-toolkit==1.0.2
    - nltk==3.6.2
    - oauthlib==3.1.1
    - omegaconf==2.0.6
    - onnx==1.9.0
    - opencc==1.1.1.post1
    - pandas==1.2.4
    - pangu==4.0.6.1
    - parameterized==0.8.1
    - pathspec==0.8.1
    - pathtools==0.1.2
#    - pesq==0.0.2
    - pip-api==0.0.20
    - pip-autoremove==0.9.1
    - pipreqs==0.4.10
    - pluggy==0.13.1
    - portalocker==2.0.0
    - promise==2.3
    - protobuf==3.17.3
    - psutil==5.8.0
    - py==1.10.0
#    - pyamg==4.1.0
    - pyannote-core==4.1
    - pyannote-database==4.1
    - pyannote-metrics==3.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pybtex==0.24.0
    - pybtex-docutils==1.0.0
    - pydub==0.25.1
    - pygments==2.9.0
    - pypinyin==0.42.0
    - pystoi==0.3.3
    - pytest==6.2.4
    - pytest-runner==5.3.1
    - pytorch-lightning==1.2.10
    - pytz==2021.1
    - pyyaml==5.3.1
    - rapidfuzz==1.4.1
    - regex==2021.4.4
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.9
    - ruamel-yaml-clib==0.2.2
    - s3transfer==0.4.2
    - sacrebleu==1.5.1
    - sacremoses==0.0.45
    - sentencepiece==0.1.95
    - sentry-sdk==1.1.0
    - shellingham==1.4.0
    - shortuuid==1.0.1
    - simplejson==3.17.2
    - smmap==4.0.0
    - snowballstemmer==2.1.0
    - sortedcontainers==2.4.0
    - sox==1.4.1
    - sphinx==4.0.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-bibtex==2.3.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - subprocess32==3.5.4
    - sympy==1.8
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - torch==1.8.1
    - torch-stft==0.1.4
    - torchmetrics==0.2.0
    - torchvision==0.9.1
    - tqdm==4.61.1
    - transformers==4.6.1
    - typed-ast==1.4.3
    - typer==0.3.2
    - typing-extensions==3.10.0.0
    - unidecode==1.2.0
    - wandb==0.10.32
    - webdataset==0.1.62
    - werkzeug==2.0.1
    - wget==3.2
    - wheel==0.36.2
    - wrapt==1.12.1
    - yarg==0.1.9
    - yarl==1.6.3
#    - youtokentome==1.0.6
#prefix: /home/dai/gpu.training/anaconda3/envs/brain4x
